sudo: required
language: bash
services:
  - docker
os:
  - linux
notifications:
  email: false
before_install:
  - sudo docker build -t abarth/divand-bluecloud .

script:
  - docker run -v "$PWD":/data -w /data --rm abarth/divand-bluecloud julia script.jl

after_success:
  - if [ "$TRAVIS_BRANCH" == master ]; then
       echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin;
       docker push abarth/divand-bluecloud;
    fi
